permalink: /:categories/:year/:month/:day/:title:output_ext

theme: jekyll-theme-slate
title: Welcome to BoDich's homepage!
description:  I am learning about GitHub Page's
<embed src="https://sumanbogati.github.io/ReadMe.txt" type="application/pdf" />
